

// Let's start manipulating the dom, yeah?

for (var i = 0; i < 45; i++) {
  var newParagraph = document.createElement('div');

  newParagraph.appendChild(document.createTextNode("This was generated by the script!"));
  
  document.getElementById("content").appendChild(newParagraph);
}



// Let's lay out some data structures, shall we?

/* CONSTANTS */
const IMAGE_DIR = "./res/stocks"


/* Files */

const meleeStocks = {
  subdir: "melee",
  chars: [
    "bowser.png",
    "dk.png",
    "doc.png",
    "falco.png",
    "falcon.png",
    "fox.png",
    "ganon.png",
    "gnw.png",
    "ics.png",
    "kirby.png",
    "link.png",
    "luigi.png",
    "mario.png",
    "marth.png",
    "mewtwo.png",
    "ness.png",
    "peach.png",
    "pichu.png",
    "pikachu.png",
    "puff.png",
    "roy.png",
    "samus.png",
    "sheik.png",
    "ylink.png",
    "yoshi.png",
    "zelda.png",
  ],
}



var roster = [];







// Event Handlers







// Helper functions
function joinImagePath(baseDir, subdir, fileName) {
  return baseDir + "/" + subdir + "/" + fileName;
}