
const MELEE = "melee";
const ULTIMATE = "ultimate";

const DEFAULT_IMG = "./res/crazyhand.png";

var gameTitle = MELEE;

var defaultImage = new Image;
defaultImage.src = DEFAULT_IMG;

var images = [];


// Let's start manipulating the dom, yeah?

for (var i = 0; i < 45; i++) {
  var newParagraph = document.createElement('div');

  newParagraph.appendChild(document.createTextNode("This was generated by the script!"));
  
  document.getElementById("content").appendChild(newParagraph);
}



// Let's lay out some data structures, shall we?

/* CONSTANTS */
const IMAGE_DIR = "./res/stocks"


/* Files */

const meleeStocks = {
  subdir: "melee",
  chars: [
    "bowser.png",
    "dk.png",
    "doc.png",
    "falco.png",
    "falcon.png",
    "fox.png",
    "ganon.png",
    "gnw.png",
    "ics.png",
    "kirby.png",
    "link.png",
    "luigi.png",
    "mario.png",
    "marth.png",
    "mewtwo.png",
    "ness.png",
    "peach.png",
    "pichu.png",
    "pikachu.png",
    "puff.png",
    "roy.png",
    "samus.png",
    "sheik.png",
    "ylink.png",
    "yoshi.png",
    "zelda.png",
  ],
}


const GAMES_DATA = "res/games.json";

function loadJSON(callback) {
  var xobj = new XMLHttpRequest();
  xobj.overrideMimeType("application/json");
  xobj.open('GET', GAMES_DATA, true);
  xobj.onreadystatechange = function() {
    if (xobj.readyState == 4 && xobj.status == "200") {
      callback(xobj.responseText);
    }
  }

  xobj.send(null);
}


function setCurrentGame(gameTitle) {
  switch (gameTitle) {
    case MELEE:
      currentGame = games.melee;
      break;
    case ULTIMATE:
      currentGame = games.ultimate;
      break;
    default:
      break;
  }

  // Set up the input ranges?

  // Set up the images?
  if (!currentGame.images) {
    loadCharacterImages(currentGame);
  }
}

function loadCharacterImages(game) {
  if (game.images) return;

  game.images = [];

  game.chars.forEach(charImage => {
    var fileName = getImagePath(game, charImage);
    var img = new Image(60, 60);
    img.classList.add("hidden");
    img.src = fileName;
    // document.body.appendChild(img);
  })
}

function getImagePath(game, charImage) {
  return IMAGE_DIR + "/" + game.subdir + "/" + charImage;
}

// Load the game data
var games = null;
var currentGame = null;
loadJSON((data) => {
  games = JSON.parse(data);
  setCurrentGame(MELEE);
});


function rangeValidationCurry(min, max) {
  return function(val) {
    return (val >= min && val <= max);
  }
}

const inputRanges = new Map([
  ["input-players", {low: 1, high: 4}],
  ["input-chars", {low: 1, high: 26}],
])

var inputFilters = [];

inputRanges.forEach(function(range, inputID) {
  inputFilters.push([inputID, rangeValidationCurry(range.low, range.high)]);
});

// Turn it into a map so we can index by ID
inputFilters = new Map(inputFilters);


// Event Handlers
function handleGenerateClick() {
  var numPlayers = document.getElementById("input-players").value;
  var numChars = document.getElementById("input-chars").value;

  // Do some basic input validation
  if (!isNumeric(numPlayers) || !isNumeric(numChars)) {
    alert("Please only input numbers");
  }

  // Now that they're numbers, we should do some validation on the ranges just to be safe
  numPlayers = parseInt(numPlayers);
  numChars = parseInt(numChars);
  // TODO: restructure data so that we validate ranges based on game state 
  // For now we'll just do the basic way though
  if (!inputFilters.get("input-players")(numPlayers) ||
      !inputFilters.get("input-chars")(numPlayers)) {
        alert("Input values are out of range!");
      }

  // Otherwise we're finally good to go!
  generateRosters(numPlayers, numChars);
}


function validateRange(inputID) {
  var input = document.getElementById(inputID);
  var range = inputRanges.get(inputID);

  if (!range) return;

  console.log("yo");

  var value = input.value;

  if (isNumeric(value)) {
    value = parseInt(value);

    if (value < range.low) {
      input.value = range.low;
    } else if (value > range.high) {
      input.value = range.high;
    }

  } else {
    input.value = "1";
  }
}

function applyStepCurry(stepVal) {
  return function(inputID) {
    var input = document.getElementById(inputID);

    if (!input) return;

    var value = input.value;

    if (isNumeric(value)) {
      // Everything is good to go!
      value = parseInt(value);

      // Increment only if within range
      if (inputFilters.get(inputID)(value + stepVal)) {
        input.value = value + stepVal;
      } else {
        input.value = "1";
      }
    } else {
      input.value = "1";
    }
  }
}

var incField = applyStepCurry(1);
var decField = applyStepCurry(-1);



// Helper Functions
function isNumeric(value) {
  return !isNaN(value);
}


// I'm going to try to restrict the input on my own
// I'm going to steal that guy's strategy of using a higher order function tho

function applyInputFilter(filter, input) {
  // For every event we need to check the
  ["input"].forEach(function(event) {
    input.addEventListener(event, function(e) {
      // Test out the filter against the value
      if (filter(e.target.value) || !e.target.value) {

      } else if (this.hasOwnProperty("oldValue")) {

      } else {
        
      }
    });
  });
}

function applyInputFilterForID(id) {  
  applyInputFilter(inputFilters.get(id), document.getElementById(id));
}


applyInputFilterForID("input-players");


// Helper functions
function joinImagePath(baseDir, subdir, fileName) {
  return baseDir + "/" + subdir + "/" + fileName;
}

function generateRosters(numPlayers, numChars) {
  var rosters = document.getElementById("rosters");
  rosters.innerHTML = "";

  // Generate a roster for each player
  for (var player = 0; player < numPlayers; player++) {
    // Create the roster parent
    var rosterParent = document.createElement("div");
    rosterParent.classList.add("roster-parent");

    // Create a spot for the roster
    var currentRoster = document.createElement("div");
    currentRoster.classList.add("roster-container");    
    var rosterID = "player-" + player;
    currentRoster.id = rosterID;

    // Add the roster to the parent
    rosterParent.appendChild(currentRoster);

    // Create the shuffle button
    var buttonContainer = createShuffleButton(rosterID, numChars);

    // Add the shuffle button to the parent
    rosterParent.appendChild(buttonContainer);

    // Add the parent to the list of all rosters
    rosters.appendChild(rosterParent);

    // Fill the roster
    fillRoster(rosterID, numChars);
  }
}

function createShuffleButton(rosterID, numChars) {
  var buttonContainer = document.createElement("div");
  var button = document.createElement("button");
  button.classList.add("shuffle");
  button.onclick = () => fillRoster(rosterID, numChars);
  button.innerText = "Shuffle";

  // Add the button to it's container
  buttonContainer.appendChild(button);

  return buttonContainer;
}




function fillRoster(rosterID, numChars) {
  var roster = document.getElementById(rosterID);
  if (!roster) {
    console.log("Error!  Roster with ID: [" + rosterID + "] not found!");
    return;
  }

  // Clear the contents of the roster
  roster.innerHTML = "";

  var rosterCharacters = getCharacters(numChars);

  // Make a cool temp list :)
  rosterCharacters.forEach(character => {
    var characterContainer = document.createElement("div");
    characterContainer.classList.add("character-container");

    characterContainer.appendChild(getStockIcon(currentGame, character));

    roster.appendChild(characterContainer);
  })
}

function getStockIcon(game, characterIndex) {
  var charImage = game.chars[characterIndex];
  var fileName = getImagePath(game, charImage);
  var img = new Image(60, 60);
  img.classList.add("stock-icon");
  img.src = fileName;

  return img;
}

function getCharacters(numChars) {
  // This is where we can do some sick random number stuff
  
  var indices = [];
  // TODO: Again, update to be more dynamic but w/e
  var characters = meleeStocks.chars;

  for (var i = 0 ; i < characters.length; i++) {
    indices.push(i);
  }

  shuffle(indices);

  indices = indices.filter((_, index) => index < numChars);

  return indices;
}

function shuffle(array) {
  var count = array.length;

  while (count > 0) {
    // Pick a random index to swap
    var index = Math.floor(Math.random() * count);

    count--;

    // Swap the elements at the specified indices
    var temp = array[count]
    array[count] = array[index];
    array[index] = temp;
  }

  return array;
}